version: "3"
services:
  node:
    image: "node"
    user: "node"
    restart: always
    depends_on:
      - "mysqldb"
      - "phpmyadmin"
    working_dir: /usr/src/app
    networks:
      - backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./:/usr/src/app
    expose:
      - 3000
    ports:
      - 9090:3000
    command: bash -c "npm run fixtures && npm run dev"
