version: "3"
services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      backend:
        aliases:
          - dbserver
    ports:
      - 3306:3306
    volumes:
      - datastore
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    networks:
      - frontend
      - backend
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=datastore
    restart: always
    depends_on:
      - mysqldb

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  datastore:
    driver: local
